apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
  namespace: mealie

spec:
  description: "Postgres cluster for the mealie application"
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
  instances: 3

  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-db-creds

  storage:
    storageClass: local-path
    size: 1Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
